Algoritmo "exercicio 2, lista 3"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Aldo Henrique
// Descrição   : Algoritmo para fazer a tabuada do 9
// Autor(a)    : Arthur Pereira de Souza
// Data atual  : 18/03/2019
Var
   produto, contador: inteiro


Inicio
   para contador de 0 ate 9 faca
      produto <- contador *9
      escreval("9 X", contador," = ",produto)
   fimpara


Fimalgoritmo